src/api/index.ts

Previously, in the instance URL ticket, the method for setting the base URL was not written optimally. So, I have revised it.

Improved condition for changing base url (#1vrd7g5)

---

changelogs/unreleased/-1z54hy7.yml
src/views/Settings.vue

Updated the UI(#1z54hy7)

---

src/index.ts
src/utils/index.ts

Implemented: function to access OMS instance with authenticated link (#99)

---

src/index.ts
src/store/productIdentification.ts

Closes #111  
Previously importing oms-api functions directly where need and now using them from context.

Implemented: oms-api context and taking oms-api functions from module options

---

src/utils/index.ts

Fixed: case of generating an authenticated link for oms(#121)

---

package-lock.json
package.json
src/components/Login.ts
src/index.ts
src/utils/firebase.ts

Had issued with DXP implementation of notifications because of pinia reactivity and Ionic not rendering. Hence, implemented the notifications system in the app and handled Firebase app initialisation centrally through DXP.

Implemented: firebase app intitialisation through DXP on login

---

src/index.ts
src/store/user.ts

Implemented: support to persist the language selected by user and fixed the issue in state persist(#175)

---

src/index.ts

Improved the code so as to export the 'getProductIdentificationValue' method from utils, to be used by the apps for productIdentifier.
**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change

Improved: code to export getProductIdentificationValue method from utils

---

src/components/Login.ts
src/index.ts
src/store/user.ts

Close: #196 
Implemented support to store the language selected as a user preference on the server.

Implemented: locale persistence as a user preference (#196)

---

package-lock.json
package.json
src/components/LanguageSwitcher.vue
src/components/ProductIdentifier.vue

Improved: app to upgrade ionic to 7.6.0(#244)

---

.github/workflows/common-firebase-hosting-release.yml

Improved: the release workflow to create a label using the tag on release

---

.github/workflows/common-firebase-hosting-release.yml

Update indentation in common-firebase-hosting-release.yml

---

src/store/productIdentification.ts

Update productIdentification options

---

src/utils/index.ts

Fixed: issue in redirection using GoToOms button by updating the regex for generating the link(#275)

---

package-lock.json
package.json

Improved: app version in package and lock file for patch release(v1.12.2)

---

.github/workflows/common-firebase-hosting-release.yml

Update: input to workflow job

---

.github/workflows/common-firebase-hosting-release.yml

Update variable for passing input to workflow job

---

package-lock.json
package.json

Improved: version in package and lock file for minor release(v1.13.0)

---

src/components/DxpAppVersionInfo.vue

Improved: dateTime method to honor the timeZone selected for the current user(#284)

---

package-lock.json
package.json

Improved: app version in package and lock file for minor release(v1.14.0)

---

src/components/DxpLogin.vue

Related Issue: https://github.com/hotwax/bopis/issues/400
Added check for firebase config to initialize firebase only if config is available.

Improved: added check for key in appFirebaseConfig (bopis-400)

---

package-lock.json
package.json

Updated: app version for the patch release (v1.14.1)

---

package-lock.json
package.json
src/components/DxpGitBookSearch.vue
src/components/index.ts
src/index.ts
src/utils/index.ts

Implemented: modal for gitbook Search functionality (#301)

---

src/components/DxpLogin.vue

#
Added a check for the firebase initialization only if subscribed to any topic.

Improved: logic to initialize firebase only if notificationPrefs are enabled

---

src/utils/firebase.ts

#
Fixed a case where on some browesers `Notification` api is not supported by adding a check of `isSupported` method

Fixed: issue when Notification api is not available on browser

---

src/store/productIdentification.ts

#324 
- Added the option of `UPCA` in productIdentifiation in the dxp-components

Improved: Added `UPCA` option in productIdentification(#324)

---

package-lock.json
package.json

Updated: app version for the patch release (v1.15.3)

---

package-lock.json
package.json

Updated: app version for the patch release (v1.15.4)

---

src/components/DxpProductIdentifier.vue
src/index.ts
src/store/productIdentification.ts

#345 
#
Improved: Fetched product identifier options dynamically (#345).

Improved: Fetched product identifier options dynamically (#345).

---

package-lock.json
package.json

Updated: app version for minor release v1.16.0.

---

src/components/DxpShopifyImg.vue

#352 
Defined a catch block for the method that checks the image url

Fixed: issue of uncaught promise when image check promise rejects(#352)

---

src/store/productIdentification.ts

#377
Added a state for fetch good identifications and exposing it to be used by apps using getters

Improved: exposed good identifications fetched from the db to be used in app(#377)

---

package-lock.json
package.json

Updated: component version for minor release v1.19.0.

---

src/components/DxpFacilitySwitcher.vue
src/store/auth.ts
src/store/user.ts

#368
- Added support to use dxp-components in the moqui based apps.
- Sending userId in user preference for moqui based apps.

Improved: added support to use dxp-components in moqui based app along with respective api calls (#368)

---

package-lock.json
package.json

Updated: app version for the patch release (v1.21.0)

---

src/components/ImageModal.vue
src/directives/imagePreview.ts
src/index.ts

#388
Created a global custom directive to be used directly as a attribute in our app for showing full image preview of thumbail images.

Implemented: custom directive globally for full image preview (#388)

---

package-lock.json
package.json

Updated: app version for the patch release (v1.22.0)

---

src/store/user.ts

#393
Added by default value of optional parameters

Improved: added default value to the userId and payload parameters (#393)

---

package-lock.json
package.json

Updated: app version for the patch release (v1.22.1)

---

package-lock.json
package.json

Improved: app version in package and lock file for patch release(v1.22.2)

---

.github/ISSUE_TEMPLATE/BUG_REPORT.yaml

Create BUG_REPORT.yaml with form validations

---

package-lock.json
package.json

Updated: dxp component version to patch release v1.22.5

---

package-lock.json
package.json

Updated: dxp component version for the minor release v1.23.0
