src/views/Search.vue, src/views/TimezoneModal.vue
Closes #
:- Worked on improving the code to assign input field to instance variable for searchbar.
Because when performing any action on search with enter key, the value of instance variable is set after the action is performed due to which wrong data is passed to API.
**IMPORTANT NOTICE** - Remember to add changelog entry
=> Improved: code to assign input field to instance variable for searchbar (#2cj8nc4).

.github/workflows/common-pull-request.yml, .github/workflows/pull-request.yml
- Removed PR build check on node v14, as v14 reached End-of-Life
- Added support to check build on node v18, as v18 is on LTS
=> Improved: pr workflow to remove node v14 and build apps on node v18

src/utils/index.ts
Related Issue: #121 
Fixed the issue when entering the full url for oms on login, and if the oms url does not contain api/ (and just contain api) at the last, then Go To OMS button does not work.
- Used a regExp in the replace function to replace the url whether it's "api" or "api/".
**IMPORTANT NOTICE** - Remember to add changelog entry
=> Fixed: issue of goToOms button working when url contains api/ but not working when it contains api only(#121)

src/components/Login.ts
Fixed firebase config-related error on login if the app is not configured for notifications support (we are not passing Firebase configurations from the app to DXP).
=> Fixed: firebase error on login if app is not configured for notifications support

src/store/user.ts
Fixed login failing due to missing locale preference configuration on user profile in Demo instance. Added undefined check for handling.
=> Fixed: login failing due to missing locale preference in userProfile

src/components/DxpImage.vue
Closes #266 
If using the `DxpImage` component from the package, update the `src` prop to pass a local data property containing the the assets url instead of directly using require with assets url in props.
Also if using local image component, update it to use `DxpImage` component.
```js
<DxpImage :src="emptyState" alt="empty state" />
.
.
emptyState: require('../assets/images/empty-state.png')
```
=> Fixed: issue in image component to render the apps local images correctly(#266)

src/components/DxpLogin.vue
=> Implemented: support to pass a redirection url to the app login from the route

src/components/DxpGitBookSearch.vue
#313
- Clearing query state of gitbook search modal to have clear console on reopening.
- Used Promise.allSettled to fetch all resources even if one api fails.
=> Improved: clearing gitbook search modal queries on modal dismiss and promise for fetching resources (#313)

src/components/DxpProductIdentifier.vue, src/index.ts
https://github.com/hotwax/bopis/issues/433
Support for permission check on the product identifier selector.
PR to test this support: https://github.com/hotwax/bopis/pull/436
=> Improved: added permission check over the product identifier (bopis-443)

src/components/DxpOmsInstanceNavigator.vue, src/index.ts
#270
Added permission check over the 'Go To OMS' button.
<b>Note:</b> I have used Commerce user view permission which is a base permission to access the commerce. Also this permission is used in deciding the email template while reset password email action in employees details page.
https://github.com/hotwax/preorder/pull/295
=> Improved: added permission check over the 'Go To OMS' button (#270)

src/components/DxpFacilitySwitcher.vue, src/components/index.ts, src/index.ts, src/store/auth.ts, src/store/user.ts
#228 
- Created the `DxpFacilitySwitcher` component with a UI that displays an `ion-card` and `ion-modal` to select a facility.  
- The list of facilities now includes the `facilityId` as well.  
- Added a feature to select a facility using radio buttons and set it as the current facility.  
- Added actions to call OMS APIs to retrieve facilities, the preferred facility, and set the current facility.  
- Added getters to retrieve all facilities and the current facility.
=> Implemented: centralized facility selector(#228)

src/components/DxpMenuFooterNavigation.vue, src/components/DxpProductIdentifier.vue, src/components/DxpProductStoreSelector.vue, src/components/index.ts, src/index.ts, src/store/auth.ts, src/store/user.ts
#193 
- Created the `DxpProductStoreSelector` component with a UI to show the product store list.
- Added a feature to select and set the product store as the current store.
- Added actions to call `oms-apis` to get the stores, preferred store, and set the current store.
- Added `getters` to retrieve all stores and the current store.
=> Implemented: centralized product store selector (#193)

src/components/DxpLogin.vue, src/components/DxpUserProfile.vue
https://github.com/hotwax/launchpad/issues/118
=> Fixed: issue in redirection using back button from the app to launchpad

src/components/DxpFacilitySwitcher.vue
#228 
For the facility selector modal, the second `ion-toolbar` component was removed, and the `ion-searchbar` was moved inside the `ion-content`.
=> Improved: removed the 2nd ion-toolbar & moved the ion-searchbar inside the ion-content(#228)

src/components/DxpFacilitySwitcher.vue
#228
- Added a check on the `Change` button to display it on the UI based on the association of the logged-in user."
- If the user has more than one facility associated with them, the Change button will be visible on the UI. Otherwise, it will not be visible if the user has only one associated facility.
=> Improved: Added a check to the "Change" button in the Facility Switcher(#228)

src/components/DxpPagination.vue, src/components/index.ts, src/index.ts
#322 
- Introduced a reusable pagination component for managing navigation across paginated data.  
- The component dynamically calculates and displays visible page numbers based on the current page and total pages, which are passed as props.  
- Emits an `updatePageCount` event with the updated page index to notify the parent component.  
- Provides controls for first, previous, next, and last page navigation, along with clear visual indicators for the currently selected page. 
=> Implemented: Dxp pagination component(#322)

src/components/DxpFacilitySwitcher.vue
#359 
- Handled the case when, after opening the modal, the user selects any facility and closes the modal without saving, the ``selectedFacility`` gets updated. To fix this, I am emptying the ``selectedFacility`` on ``@didDismiss``.  
- Updating the ``selectedFacilityId`` ref on ``@didPresent`` to set the current facility correctly.  
=> Fixed: When the modal is reopened, no option should appear pre-selected unless it was previously saved(#359)

src/components/DxpFacilitySwitcher.vue
#
When searching for a facility, and if any of the facility has missing name, then the facility search does not completes, so added an optional chaining condition to complete the search even when missing facility name.
=> Fixed: facility search not working when any of the facility has missing name

src/components/DxpMenuFooterNavigation.vue, src/index.ts, src/store/user.ts
#363 
- Added support for fetching all product stores, regardless of any parameters.  
- Dxp uses the `getEComStores` service from `oms-api`, passed from the application.  
- The `getEComStores` action updates Dxp's `eComStores` state in the product store selector.  
- Also updated the `DxpMenuFooterNavigation` component to use the `dxp-components` state for retrieving and updating product stores.  
=> Implemented: Added support for fetching all product stores (#363)

src/components/DxpTimeZoneSwitcher.vue
https://github.com/hotwax/preorder/issues/301
#
Now the spinner shows while fetching timezone to inform user that fetching is in progress.
=> Improved: the code to Show spinner while fetching timezone to inform user that fetching in progress.(#301)

src/components/DxpMenuFooterNavigation.vue
https://github.com/hotwax/job-manager/issues/725
#
Fixed: Empty Space Below Favourite Product Store Name on Login When No Shopify Shop is Linked (job-manager-725)
=> Fixed: Empty Space Below Favourite Product Store Name on Login When No Shopify Shop is Linked (job-manager-725)

src/components/DxpProductIdentifier.vue, src/store/productIdentification.ts
#350 
- Added support to show the description of the good identification type instead of the typeId
- Previously, the getters of the product identification state returned only the `goodIdentificationTypeId`, and we directly displayed the `typeId` in our application. After this change, the getter will return an array of objects, each containing the `goodIdentificationTypeId` along with its description.
- So currently, wherever we are using this to display the identification list using a loop, instead of directly using the looped value, use dot notation (`.`) to access the properties, i.e., `goodIdentificationTypeId` and `description`.
=> Improved: Updated the product identifier selection (#350)

src/components/DxpLogin.vue, src/index.ts, src/store/auth.ts, src/utils/index.ts
Added isEmbedded flag passed from Embedded-Launchpad and passed it to app's login context.
Any app that is refered from the Embedded-Launchpad have to fetch and handle re-routing to respective lauchpads
Linked Issue : #408
=> Added isEmbedded flag to app's login context

src/components/DxpLogin.vue, src/store/auth.ts, src/utils/index.ts
#408 
When redirecting to the embedded launchpad, we redirect successfully but without the shop and host becase the initial context when the app was loaded from the Admin or POS is lost when we redirected to our PW App. It it seen that if we pass only the shop and host with the URL then the the app is opened in Admin with proper context.
To verify the same behaviour in the POS, we've to test.
This PR is for POC in Shopify POS.
=> Added shop and host in auth state and updated get app login util method
